-- Disable RLS for development
-- RLS will be re-enabled in production with proper connection management

ALTER TABLE "Process" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ImpactAssessment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "RecoveryObjective" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Dependency" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "BusinessResource" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "VendorDetails" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkaroundProcedure" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ResourceDependency" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProcessResourceLink" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "TieredResourceRequirement" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ExerciseRecord" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FollowUpAction" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Diagram" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Incident" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Risk" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Threat" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategicPlanning" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "RiskTreatment" DISABLE ROW LEVEL SECURITY;
